import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={"Access-Control-Allow-Origin":"https://sniperscoop2-spec.github.io","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Vary":"Origin"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:cors});
function eq(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let v=0;for(let i=0;i<a.length;i++)v|=a[i]^b[i];return v===0}
async function hmac(k:Uint8Array,d:string){const c=await crypto.subtle.importKey("raw",k,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",c,new TextEncoder().encode(d)))}
async function sha(v:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)));return Array.from(d).map(x=>x.toString(16).padStart(2,"0")).join("")}
function secret(){const x=Deno.env.get("SUPABASE_SECRET_KEYS");if(x){try{const p=JSON.parse(x);if(typeof p?.default==="string")return p.default;const v=Object.values(p??{}).find(v=>typeof v==="string");if(typeof v==="string")return v}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??null}
async function db(path:string,o:RequestInit={}){const u=Deno.env.get("SUPABASE_URL"),s=secret();if(!u||!s)throw Error("server_credentials_unavailable");const r=await fetch(`${u}/rest/v1/${path}`,{...o,headers:{apikey:s,Authorization:`Bearer ${s}`,"Content-Type":"application/json",...(o.headers??{})}}),t=await r.text();if(!r.ok)throw Error(`db_error:${r.status}`);return t?JSON.parse(t):null}
async function verify(raw:string,bot:string){if(!raw||raw.length>10000)return{ok:false,error:"invalid_init_data"};const p=new URLSearchParams(raw),h=p.get("hash"),a=Number(p.get("auth_date")??0);if(!h||!/^[0-9a-f]{64}$/i.test(h)||!Number.isSafeInteger(a)||a<=0)return{ok:false,error:"invalid_init_data"};const age=Math.floor(Date.now()/1000)-a;if(age<-60||age>600)return{ok:false,error:"expired_init_data"};const data=[...p.entries()].filter(([k])=>k!=="hash").sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n");const sk=await hmac(new TextEncoder().encode("WebAppData"),bot),calc=await hmac(sk,data),sup=new Uint8Array(h.match(/.{2}/g)!.map(x=>parseInt(x,16)));if(!eq(calc,sup))return{ok:false,error:"invalid_signature"};let user:any=null;try{user=JSON.parse(p.get("user")??"null")}catch{}const id=Number(user?.id);if(!Number.isSafeInteger(id)||id<=0)return{ok:false,error:"invalid_user"};return{ok:true,id,user}}
async function session(playerId:string){const r=new Uint8Array(32);crypto.getRandomValues(r);const token=Array.from(r).map(x=>x.toString(16).padStart(2,"0")).join("");const hash=await sha(token),expires=new Date(Date.now()+900000).toISOString();await db(`make_money_sessions?expires_at=lt.${encodeURIComponent(new Date().toISOString())}`,{method:"DELETE"});await db("make_money_sessions",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({token_hash:hash,player_id:playerId,expires_at:expires})});return{token,expires}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({ok:false,error:"POST_REQUIRED"},405);try{const b=await req.json(),bot=Deno.env.get("TELEGRAM_BOT_TOKEN");if(!bot)return json({ok:false,error:"TELEGRAM_BOT_TOKEN_NOT_CONFIGURED"},503);const v=await verify(typeof b?.initData==="string"?b.initData:"",bot);if(!v.ok)return json({ok:false,error:v.error},401);const u=v.user,p=await db("make_money_players?on_conflict=telegram_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify({telegram_id:v.id,username:typeof u.username==="string"?u.username:null,first_name:typeof u.first_name==="string"?u.first_name:"",last_name:typeof u.last_name==="string"?u.last_name:null,avatar_url:typeof u.photo_url==="string"?u.photo_url:null})});const player=Array.isArray(p)?p[0]:p;if(!player?.id)throw Error("player_missing");const s=await session(player.id);return json({ok:true,session:{token:s.token,expires_at:s.expires},player:{id:player.id,telegram_id:player.telegram_id,username:player.username,first_name:player.first_name,last_name:player.last_name,avatar_url:player.avatar_url??null,balance:player.balance}})}catch(e){console.error(e);return json({ok:false,error:"AUTH_SERVER_ERROR"},500)}})