const CASES_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-cases';
let casesData=[],caseCatalog=[],caseInventory=[],caseBusy=false,caseView='cases';
const caseFetch=async body=>fetch(CASES_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${window.mmSessionToken}`},body:JSON.stringify(body),cache:'no-store'});
const caseOp=()=>crypto.randomUUID().replace(/-/g,'');
const caseFmt=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:2});
const rarityLabel=r=>({common:'Common',uncommon:'Uncommon',rare:'Rare',epic:'Epic',legendary:'Legendary'}[r]||r);
function caseError(e){return ({INSUFFICIENT_BALANCE:'Not enough MM.',SESSION_EXPIRED:'Session expired. Reopen the Mini App.',INVALID_CASE:'Invalid case.',CASES_SERVER_ERROR:'Case server error.'}[e.message]||`Case error (${e.message||'unknown'}).`);}
function renderCases(){const root=document.getElementById('caseList');if(!root)return;root.replaceChildren();casesData.forEach(c=>{const card=document.createElement('article');card.className='case-card';card.innerHTML=`<div class="case-art"><div class="case-glow"></div><strong>CASE</strong><span>${c.price>=5000?'LEGEND':c.price>=500?'ELITE':'STARTER'}</span></div><h3>${c.display_name}</h3><p>Random item · rarity based</p><button type="button" class="case-open" data-case="${c.case_id}">Open · ${caseFmt(c.price)} MM</button>`;root.append(card);});root.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>openCase(b.dataset.case)));}
function renderInventory(){const root=document.getElementById('inventoryList');if(!root)return;root.replaceChildren();caseInventory.forEach(i=>{const card=document.createElement('article');card.className=`inventory-item rarity-${i.rarity}`;card.innerHTML=`<div class="item-icon">✦</div><div class="item-info"><strong>${i.display_name}</strong><small>${rarityLabel(i.rarity)} · ${caseFmt(i.sell_value)} MM each</small></div><b>×${i.quantity}</b><button type="button" data-sell="${i.item_id}">Sell</button>`;root.append(card);});if(!caseInventory.length)root.innerHTML='<div class="inventory-empty">Inventory empty. Open a case to receive an item.</div>';}
function renderCatalog(){const root=document.getElementById('catalogList');if(!root)return;root.replaceChildren();caseCatalog.forEach(i=>{const card=document.createElement('article');card.className=`catalog-item rarity-${i.rarity}`;card.innerHTML=`<div class="item-icon">✦</div><div><strong>${i.display_name}</strong><small>${rarityLabel(i.rarity)} · Sell ${caseFmt(i.sell_value)} MM</small></div>`;root.append(card);});}
function renderCasePage(){renderCases();renderInventory();renderCatalog();document.getElementById('casesView')?.classList.toggle('active',caseView==='cases');document.getElementById('inventoryView')?.classList.toggle('active',caseView==='inventory');document.getElementById('catalogView')?.classList.toggle('active',caseView==='catalog');}
async function loadCases(){if(!window.mmSessionToken)return;try{const r=await caseFetch({action:'status'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);casesData=d.cases||[];caseInventory=d.inventory||[];caseCatalog=d.catalog||[];setBalanceFromCase(d.balance);renderCasePage();}catch(e){const s=document.getElementById('casesStatus');if(s)s.textContent=caseError(e);}}
async function openCase(caseId){if(caseBusy)return;const c=casesData.find(x=>x.case_id===caseId);if(!c)return;if(Number(window.mmBalance||0)<Number(c.price)){const s=document.getElementById('casesStatus');if(s)s.textContent='Not enough MM.';return;}caseBusy=true;const overlay=document.getElementById('caseOpening'),wrap=document.querySelector('.case-strip-wrap'),strip=document.getElementById('caseStrip'),result=document.getElementById('caseResult');overlay.hidden=false;result.hidden=true;strip.replaceChildren();const pool=caseCatalog.filter(x=>x.item_id.startsWith(caseId.replace('case_','case')));for(let n=0;n<28;n++){const i=pool[n%pool.length],e=document.createElement('div');e.className=`roll-item rarity-${i.rarity}`;e.innerHTML=`<span>✦</span><strong>${i.display_name}</strong><small>${rarityLabel(i.rarity)}</small>`;strip.append(e);}const targetIndex=23;const itemWidth=156,gap=8;const target=-(targetIndex*(itemWidth+gap))+(wrap.clientWidth/2-itemWidth/2);strip.style.setProperty('--target-x',`${target}px`);try{const req=caseFetch({action:'open',case_id:caseId,operation_key:caseOp()});await new Promise(r=>requestAnimationFrame(r));strip.classList.add('rolling');const r=await req,d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);await new Promise(r=>setTimeout(r,4300));const won=caseCatalog.find(i=>i.item_id===d.item_id);result.hidden=false;result.innerHTML=`<div class="result-rarity rarity-${won?.rarity||'common'}">${rarityLabel(won?.rarity)}</div><strong>${won?.display_name||d.item_id}</strong><span>Added to Inventory · ${caseFmt(won?.sell_value)} MM value</span><button type="button" id="caseClose">Continue</button>`;document.getElementById('caseClose').onclick=()=>{overlay.hidden=true;result.hidden=true;strip.classList.remove('rolling');strip.style.removeProperty('--target-x');loadCases();};setBalanceFromCase(d.balance);}catch(e){overlay.hidden=true;strip.classList.remove('rolling');const s=document.getElementById('casesStatus');if(s)s.textContent=caseError(e);}finally{caseBusy=false;renderCasePage();}}
function setBalanceFromCase(v){const b=Number(v||0);window.mmBalance=b;const e=document.getElementById('balance');if(e)e.textContent=caseFmt(b);const h=document.getElementById('headerBalance');if(h)h.textContent=`${caseFmt(b)} MM`;window.dispatchEvent(new CustomEvent('make-money-balance-updated',{detail:{balance:b}}));}
async function sellItem(id,qty=1){if(caseBusy)return;caseBusy=true;try{const r=await caseFetch({action:'sell',item_id:id,quantity:qty}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);setBalanceFromCase(d.balance);await loadCases();}catch(e){const s=document.getElementById('casesStatus');if(s)s.textContent=caseError(e);}finally{caseBusy=false;renderCasePage();}}
async function sellAllItems(){if(caseBusy||!caseInventory.length)return;caseBusy=true;try{const r=await caseFetch({action:'sell_all'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);setBalanceFromCase(d.balance);await loadCases();}catch(e){const s=document.getElementById('casesStatus');if(s)s.textContent=caseError(e);}finally{caseBusy=false;renderCasePage();}}
function bindCases(){document.getElementById('casesTab')?.addEventListener('click',()=>{caseView='cases';renderCasePage();});document.getElementById('inventoryTab')?.addEventListener('click',()=>{caseView='inventory';renderCasePage();});document.getElementById('viewAllItems')?.addEventListener('click',()=>{caseView='catalog';renderCasePage();});document.getElementById('sellAllItems')?.addEventListener('click',sellAllItems);document.getElementById('inventoryList')?.addEventListener('click',e=>{const b=e.target.closest('[data-sell]');if(b)sellItem(b.dataset.sell,1);});window.addEventListener('make-money-authenticated',loadCases);window.addEventListener('make-money-balance-updated',renderCasePage);loadCases();}
window.mmLoadCases=loadCases;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindCases,{once:true});else bindCases();