const HOME_RANKING_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-ranking';
const HOME_CASES_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-cases';
const HOME_MINING_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-mining';
const HOME_JOBS_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-jobs';
const HOME_RE_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-real-estate';
let homeItems=[],homeAssets=[],homeLoading=false,homeRefreshQueued=false;
const homeFmt=v=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2});
const homeJson=async(url,body)=>{if(!window.mmSessionToken)return null;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${window.mmSessionToken}`},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||`HTTP ${r.status}`);return d;};
function homeProfileOpen(){const m=document.getElementById('profileSheet');if(m){m.hidden=false;loadHomeRank();renderHomeProfile();}}
function homeProfileClose(){const m=document.getElementById('profileSheet');if(m)m.hidden=true;}
async function loadHomeRank(){const e=document.getElementById('profileRank');if(!e||!window.mmSessionToken)return;try{const d=await homeJson(HOME_RANKING_API,{limit:50});const me=(d?.ranking||[]).find(x=>x.is_me);e.textContent=me?`#${Number(me.rank)}`:'—';}catch{e.textContent='—';}}
function homePlayTime(){const key='mm_home_play_seconds';const current=Math.max(0,Number(localStorage.getItem(key)||0));const started=Number(window.mmHomeSessionStarted||Date.now());const total=current+Math.max(0,Math.floor((Date.now()-started)/1000));localStorage.setItem(key,String(total));const h=Math.floor(total/3600),m=Math.floor((total%3600)/60);return `${h}h ${m}m`;}
function renderHomeProfile(){const source=document.querySelector('#avatar img');const button=document.getElementById('homeProfileButton');const large=document.getElementById('profileAvatarLarge');const makeAvatar=()=>source?source.cloneNode(true):Object.assign(document.createElement('span'),{textContent:'◎'});if(button){button.replaceChildren(makeAvatar());}if(large){large.replaceChildren(makeAvatar());}const name=document.getElementById('name')?.textContent||'Player';const username=document.getElementById('username')?.textContent||'Telegram user';const pn=document.getElementById('profileName');const pu=document.getElementById('profileUsername');const pt=document.getElementById('profilePlayTime');const pb=document.getElementById('profileBalance');if(pn)pn.textContent=name;if(pu)pu.textContent=username;if(pt)pt.textContent=homePlayTime();if(pb)pb.textContent=`${homeFmt(window.mmBalance)} MM`;}
function addHomeAsset(key,icon,name,sub,rate){const n=Number(rate);if(!Number.isFinite(n)||n<=0)return;const existing=homeAssets.find(a=>a.key===key);if(existing){existing.rate+=n;return;}homeAssets.push({key,icon,name,sub,rate:n});}
function normalizeItems(items){const map=new Map();for(const i of Array.isArray(items)?items:[]){if(!i?.item_id)continue;const prev=map.get(i.item_id);if(prev)prev.quantity=Number(prev.quantity||0)+Number(i.quantity||0);else map.set(i.item_id,{...i,quantity:Number(i.quantity||0)});}return [...map.values()];}
function renderHomeAssets(){const list=document.getElementById('homeAssetList'),income=document.getElementById('homeAssetsIncome'),items=document.getElementById('homeItemGrid'),count=document.getElementById('homeItemsCount');if(!list)return;list.replaceChildren();let perHour=0;for(const a of homeAssets){perHour+=a.rate;const row=document.createElement('div');row.className='home-asset-row';const icon=document.createElement('div');icon.className='home-asset-icon';icon.textContent=a.icon;const info=document.createElement('div');info.className='home-asset-info';const strong=document.createElement('strong');strong.textContent=a.name;const small=document.createElement('small');small.textContent=a.sub;info.append(strong,small);const rate=document.createElement('strong');rate.className='home-asset-rate';rate.textContent=`+${homeFmt(a.rate)}/h`;row.append(icon,info,rate);list.append(row);}if(!homeAssets.length)list.innerHTML='<div class="home-empty">No active income assets yet.</div>';if(income)income.textContent=`+${homeFmt(perHour)} MM / hour`;if(items){items.replaceChildren();homeItems.slice(0,6).forEach(i=>{const c=document.createElement('div');c.className='home-item-card';const visual=document.createElement('div');visual.className='item-visual';visual.textContent='✦';const name=document.createElement('strong');name.textContent=i.display_name||'Item';const value=document.createElement('small');value.textContent=`${homeFmt(i.sell_value)} MM · ×${Number(i.quantity||0)}`;c.append(visual,name,value);items.append(c);});if(!homeItems.length)items.innerHTML='<div class="home-empty">No items collected yet.</div>';}if(count)count.textContent=homeItems.reduce((n,i)=>n+Number(i.quantity||0),0);}
async function loadHomeAssets(){if(homeLoading||!window.mmSessionToken)return;homeLoading=true;try{const [mining,jobs,re,items]=await Promise.allSettled([homeJson(HOME_MINING_API,{action:'status'}),homeJson(HOME_JOBS_API,{action:'list'}),homeJson(HOME_RE_API,{action:'list'}),homeJson(HOME_CASES_API,{action:'status'})]);const nextAssets=[];const add=(key,icon,name,sub,rate)=>{const n=Number(rate);if(!Number.isFinite(n)||n<=0)return;const old=nextAssets.find(x=>x.key===key);if(old)old.rate+=n;else nextAssets.push({key,icon,name,sub,rate:n});};if(mining.status==='fulfilled'){const current=(mining.value.mining||[]).find(x=>x.owned)||(mining.value.mining||[])[0];if(current)add(`mining:${current.level}`, '⛏️',current.name||'Mining',`Level ${current.level||1}`,Number(current.rate_per_hour||0));}if(jobs.status==='fulfilled'){const active=(jobs.value.jobs||[]).find(x=>x.active);if(active)add(`job:${active.job_id}`,'💼',active.name||'Job','Active job',Number(active.income_per_hour||0));}if(re.status==='fulfilled'){for(const p of (re.value.properties||[]).filter(x=>Number(x.owned_units||0)>0)){add(`property:${p.property_id||p.name}`,'🏢',p.name||'Property',`${Number(p.owned_units||0)} owned`,Number(p.income_per_day||0)*Number(p.owned_units||0)/24);}}homeAssets=nextAssets;homeItems=items.status==='fulfilled'?normalizeItems(items.value.inventory):[];renderHomeAssets();renderHomeProfile();}catch(e){console.error('Home dashboard error',e);}finally{homeLoading=false;if(homeRefreshQueued){homeRefreshQueued=false;loadHomeAssets();}}}
function queueHomeRefresh(){if(homeLoading){homeRefreshQueued=true;return;}loadHomeAssets();}
function homeBind(){window.mmHomeSessionStarted=Date.now();document.getElementById('homeProfileButton')?.addEventListener('click',homeProfileOpen);document.getElementById('profileClose')?.addEventListener('click',homeProfileClose);document.getElementById('profileSheet')?.addEventListener('click',e=>{if(e.target.id==='profileSheet')homeProfileClose();});document.getElementById('homeInventoryButton')?.addEventListener('click',()=>window.mmNavigate?.('inventory'));window.addEventListener('make-money-authenticated',()=>{renderHomeProfile();queueHomeRefresh();});window.addEventListener('make-money-balance-updated',()=>{renderHomeProfile();queueHomeRefresh();});if(window.mmSessionToken){renderHomeProfile();queueHomeRefresh();}}
window.mmLoadHome=loadHomeAssets;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',homeBind,{once:true});else homeBind();