const MINING_MODULES_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-mining';
const MINING_BASE='https://raw.githubusercontent.com/sniperscoop2-spec/make-money/b43cd319dfbe7070d2a193f16817a2bdfcbeb2b3/telegram-mining.js';
let liveMiningState=null,liveMiningTimer=null,liveMiningPoll=null;
async function liveMiningLoad(){if(!window.mmSessionToken)return;try{const r=await fetch(MINING_MODULES_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${window.mmSessionToken}`},body:JSON.stringify({action:'status'}),cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)return;const rows=Array.isArray(d.mining)?d.mining:[];const current=rows.filter(x=>x.owned).sort((a,b)=>Number(b.level||0)-Number(a.level||0))[0]||rows.find(x=>Number(x.level)===1);if(!current)return;liveMiningState={last:new Date(current.last_claim_at||Date.now()).getTime(),next:new Date(current.next_claim_at||Date.now()).getTime(),rate:Number(current.rate_per_hour||10)};liveMiningRender();}catch{}}
function liveMiningRender(){const box=document.getElementById('miningClaimProgress');if(!box||!liveMiningState)return;const reward=box.querySelector('#miningProgressReward'),fill=box.querySelector('.mining-progress-fill'),remaining=box.querySelector('.mining-progress-remaining');if(!reward||!fill||!remaining)return;const now=Date.now(),hour=3600000,elapsed=Math.max(0,now-liveMiningState.last),hours=Math.min(24,Math.floor(elapsed/hour)),claimable=hours*liveMiningState.rate;const next=Math.max(0,liveMiningState.next-now);const progress=Math.min(100,Math.max(0,((elapsed%hour)/hour)*100));reward.textContent=`+${Number(claimable).toLocaleString('en-US',{maximumFractionDigits:4})} MM`;fill.style.width=`${next<=0?'100':progress}%`;remaining.textContent=next<=0?'Ready to claim':`Available in ${(()=>{const s=Math.ceil(next/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return `${h}h ${String(m).padStart(2,'0')}m ${String(sec).padStart(2,'0')}s`;})()}`;}
function liveMiningStart(){if(liveMiningTimer)clearInterval(liveMiningTimer);if(liveMiningPoll)clearInterval(liveMiningPoll);liveMiningTimer=setInterval(liveMiningRender,1000);liveMiningPoll=setInterval(liveMiningLoad,10000);liveMiningLoad();}
async function liveMiningBoot(){const s=document.createElement('script');s.src=MINING_BASE;s.onload=()=>liveMiningStart();s.onerror=()=>liveMiningStart();document.head.appendChild(s);}
window.addEventListener('make-money-authenticated',liveMiningStart);window.addEventListener('make-money-balance-updated',liveMiningLoad);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',liveMiningBoot,{once:true});else liveMiningBoot();
