const MARKET_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-crypto-market';
let marketBusy=false,marketAssets=[],marketHoldings={},marketSelected='BITX',marketTimer=null;
const marketFetch=(body)=>{const token=window.mmSessionToken;const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);return fetch(MARKET_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify(body),cache:'no-store',signal:c.signal}).finally(()=>clearTimeout(t));};
const marketKey=()=>window.crypto?.randomUUID?crypto.randomUUID().replace(/-/g,''):Array.from(crypto.getRandomValues(new Uint8Array(24)),x=>x.toString(16).padStart(2,'0')).join('');
const mf=v=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:4});
function marketAsset(){return marketAssets.find(a=>a.symbol===marketSelected)||marketAssets[0];}
function marketPortfolio(){return marketAssets.reduce((sum,a)=>sum+Number(marketHoldings[a.symbol]?.value||0),0);}
function drawMarketChart(asset){const box=document.getElementById('marketChart');if(!box||!asset)return;const values=(asset.history||[]).map(Number).filter(Number.isFinite);if(values.length<2){box.innerHTML='';return;}const min=Math.min(...values),max=Math.max(...values),range=Math.max(max-min,.000001);const points=values.map((v,i)=>`${(i/(values.length-1))*100},${92-((v-min)/range)*76}`).join(' ');const direction=Number(asset.change_pct||0)>=0?'up':'down';box.innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="${asset.symbol} price chart"><polyline class="market-line-${direction}" points="${points}" fill="none" pathLength="1"/></svg>`;}
function renderMarket(){const asset=marketAsset();if(!asset)return;const value=marketPortfolio();const total=document.getElementById('marketPortfolioValue');if(total)total.textContent=`${mf(value)} MM`;const title=document.getElementById('marketSelectedName');if(title)title.textContent=`${asset.icon} ${asset.name}`;const symbol=document.getElementById('marketSelectedSymbol');if(symbol)symbol.textContent=asset.symbol;const price=document.getElementById('marketSelectedPrice');if(price)price.textContent=`${mf(asset.price)} MM`;const change=document.getElementById('marketSelectedChange');if(change){change.textContent=`${asset.change_pct>=0?'+':''}${Number(asset.change_pct||0).toFixed(2)}%`;change.className=asset.change_pct>=0?'market-up':'market-down';}drawMarketChart(asset);const list=document.getElementById('cryptoAssetList');if(list){list.replaceChildren();for(const a of marketAssets){const row=document.createElement('button');row.type='button';row.className=`crypto-asset-row${a.symbol===marketSelected?' selected':''}`;row.innerHTML=`<span class="crypto-icon">${a.icon}</span><span class="crypto-name"><strong>${a.name}</strong><small>${a.symbol}</small></span><span class="crypto-price"><strong>${mf(a.price)}</strong><small class="${a.change_pct>=0?'market-up':'market-down'}">${a.change_pct>=0?'+':''}${Number(a.change_pct||0).toFixed(2)}%</small></span>`;row.onclick=()=>{marketSelected=a.symbol;renderMarket();};list.append(row);}}const h=marketHoldings[asset.symbol];const holding=document.getElementById('marketHolding');if(holding)holding.textContent=`Holding: ${mf(h?.quantity||0)} ${asset.symbol} · ${mf(h?.value||0)} MM`;const buy=document.getElementById('marketBuy'),sell=document.getElementById('marketSell');const qty=Number(document.getElementById('marketQuantity')?.value||0);if(buy)buy.disabled=marketBusy||!Number.isFinite(qty)||qty<=0||Number(window.mmBalance||0)<qty*asset.price*1.01;if(sell)sell.disabled=marketBusy||!Number.isFinite(qty)||qty<=0||Number(h?.quantity||0)<qty;}
async function marketStatus(){if(!window.mmSessionToken)return;try{const r=await marketFetch({action:'status'}),d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||`HTTP ${r.status}`);marketAssets=Array.isArray(d.assets)?d.assets:[];marketHoldings=d.holdings&&typeof d.holdings==='object'?d.holdings:{};if(d.balance!==undefined){window.mmBalance=Number(d.balance);const b=document.getElementById('balance');if(b)b.textContent=mf(d.balance);const hb=document.getElementById('headerBalance');if(hb)hb.textContent=`${mf(d.balance)} MM`;}const s=document.getElementById('marketStatus');if(s)s.textContent='';renderMarket();}catch(e){const s=document.getElementById('marketStatus');if(s)s.textContent=e.name==='AbortError'?'Market request timed out.':'Crypto Market unavailable.';}}
async function marketTrade(side){if(marketBusy)return;const asset=marketAsset(),input=document.getElementById('marketQuantity'),qty=Number(input?.value||0);if(!asset||!Number.isFinite(qty)||qty<=0)return;marketBusy=true;renderMarket();const status=document.getElementById('marketStatus');if(status)status.textContent=side==='buy'?`Buying ${qty} ${asset.symbol}...`:`Selling ${qty} ${asset.symbol}...`;try{const r=await marketFetch({action:'trade',symbol:asset.symbol,side,quantity:qty,operation_key:marketKey()}),d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||`HTTP ${r.status}`);window.mmBalance=Number(d.balance);const b=document.getElementById('balance');if(b)b.textContent=mf(d.balance);const hb=document.getElementById('headerBalance');if(hb)hb.textContent=`${mf(d.balance)} MM`;if(status)status.textContent=`✓ ${side==='buy'?'Bought':'Sold'} ${mf(d.quantity)} ${d.symbol} at ${mf(d.price)} MM · fee ${mf(d.fee)} MM.`;await marketStatus();window.dispatchEvent(new CustomEvent('make-money-balance-updated',{detail:{balance:Number(d.balance)}}));}catch(e){const map={INSUFFICIENT_BALANCE:'Not enough MM.',INSUFFICIENT_HOLDINGS:'Not enough coins held.',INVALID_QUANTITY:'Invalid quantity.',SESSION_EXPIRED:'Session expired. Reopen the Mini App.'};if(status)status.textContent=map[e.message]||`Trade failed (${e.message}).`;}finally{marketBusy=false;renderMarket();}}
function marketBind(){document.getElementById('marketBuy')?.addEventListener('click',()=>marketTrade('buy'));document.getElementById('marketSell')?.addEventListener('click',()=>marketTrade('sell'));document.getElementById('marketQuantity')?.addEventListener('input',renderMarket);window.addEventListener('make-money-authenticated',()=>marketStatus());window.addEventListener('make-money-balance-updated',renderMarket);marketStatus();if(!marketTimer)setInterval(()=>{if(document.getElementById('cryptoMarket')?.hidden===false)marketStatus();},15000);}
window.mmLoadCryptoMarket=marketStatus;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',marketBind,{once:true});else marketBind();
