const CASINO_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-casino';
let casinoBusy=false,casinoBet=10,casinoChoices=[],casinoGame='roulette',blackjackRoundId=null,blackjackActive=false,blackjackData=null,rouletteAnimationFrame=null,slotsAutoOn=false,slotsAutoTimer=null;
const casinoOriginalFetch=window.fetch.bind(window);
function casinoSessionValid(){return Boolean(window.mmSessionToken&&Date.now()<Number(window.mmSessionExpiresAt||0));}
function casinoFormat(v){return Number(v||0).toLocaleString('en-US',{maximumFractionDigits:4});}
function casinoValidBet(v){const n=Number(v);return Number.isSafeInteger(n)&&n>=10;}
function casinoOperationKey(){if(window.crypto?.randomUUID)return window.crypto.randomUUID().replace(/-/g,'');const b=new Uint8Array(24);crypto.getRandomValues(b);return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
async function casinoFetch(body){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{return await casinoOriginalFetch(CASINO_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${window.mmSessionToken}`},body:JSON.stringify(body),cache:'no-store',signal:c.signal});}finally{clearTimeout(t);}}
function setCasinoStatus(m){const e=document.getElementById('casinoStatus');if(e)e.textContent=m;}
function setBalanceFromCasino(v){const b=Number(v||0);window.mmBalance=b;const e=document.getElementById('balance');if(e)e.textContent=casinoFormat(b);const h=document.getElementById('headerBalance');if(h)h.textContent=`${casinoFormat(b)} MM`;window.dispatchEvent(new CustomEvent('make-money-balance-updated',{detail:{balance:b}}));}
function casinoError(err,game){const m={INSUFFICIENT_BALANCE:'Not enough MM for this bet.',SESSION_EXPIRED:'Session expired. Reopen the Mini App.',INVALID_BET:'Invalid bet.',INVALID_CHOICE:'Invalid roulette bet.',BLACKJACK_ROUND_FINISHED:'This blackjack round is already finished.',BLACKJACK_ROUND_NOT_FOUND:'Blackjack round not found.',PLAYER_NOT_FOUND:'Player account not found.',CASINO_SERVER_ERROR:`${game} server error.`,INVALID_OPERATION_KEY:'Invalid operation. Please retry.'};return err?.name==='AbortError'?'Casino request timed out.':m[err?.message]||`${game} unavailable (${err?.message||'unknown error'}).`;}
const rouletteChoices=[['red','🔴 Red','1:1'],['black','⚫ Black','1:1'],['odd','Odd','1:1'],['even','Even','1:1'],['low','1–18','1:1'],['high','19–36','1:1'],['dozen1','1st 12','2:1'],['dozen2','2nd 12','2:1'],['dozen3','3rd 12','2:1'],['column1','Column 1','2:1'],['column2','Column 2','2:1'],['column3','Column 3','2:1']];
function makeRouletteButton(choice,label,payout){const b=document.createElement('button');b.type='button';b.dataset.choice=choice;b.className='roulette-choice-button';if(choice==='red')b.classList.add('red');if(choice==='black')b.classList.add('black');b.innerHTML=`<span>${label}</span><small>${payout}</small>`;return b;}
function ensureRouletteChoices(){const game=document.getElementById('casinoRoulette');if(!game)return;let root=document.getElementById('rouletteBetChoices');if(!root){root=document.createElement('div');root.id='rouletteBetChoices';root.className='roulette-bet-choices';const spin=document.getElementById('rouletteSpin');game.insertBefore(root,spin||null);}root.replaceChildren();const groups=[['Outside bets · 1:1',rouletteChoices.slice(0,6)],['Dozens & columns · 2:1',rouletteChoices.slice(6)]];groups.forEach(([title,items])=>{const label=document.createElement('div');label.className='casino-label';label.textContent=title;root.append(label);const grid=document.createElement('div');grid.className='roulette-choice-grid';items.forEach(x=>grid.append(makeRouletteButton(...x)));root.append(grid);});}
function selectedRouletteTotal(){return casinoBet*casinoChoices.length;}
function renderCasino(){document.querySelectorAll('.casino-tab').forEach(b=>b.classList.toggle('active',b.dataset.game===casinoGame));document.querySelectorAll('.casino-game').forEach(g=>g.classList.toggle('active',g.id===`casino${casinoGame[0].toUpperCase()+casinoGame.slice(1)}`));document.querySelectorAll('.casino-bets [data-bet]').forEach(b=>{const s=Number(b.dataset.bet)===casinoBet;b.classList.toggle('selected',s);b.disabled=casinoBusy||!casinoSessionValid()||Number(window.mmBalance||0)<Number(b.dataset.bet);});document.querySelectorAll('.casino-custom-bet').forEach(i=>{if(document.activeElement!==i)i.value=casinoValidBet(casinoBet)?casinoBet:'';i.disabled=casinoBusy||!casinoSessionValid();i.classList.toggle('selected',casinoValidBet(casinoBet)&&Number(i.value)===casinoBet);i.setAttribute('aria-invalid',i.value!==''&&!casinoValidBet(i.value)?'true':'false');});document.querySelectorAll('#rouletteBetChoices [data-choice]').forEach(b=>{const s=casinoChoices.includes(b.dataset.choice);b.classList.toggle('selected',s);b.disabled=casinoBusy||!casinoSessionValid()||(!s&&selectedRouletteTotal()+casinoBet>Number(window.mmBalance||0));});const rs=document.getElementById('rouletteSpin');if(rs){const total=selectedRouletteTotal();rs.disabled=casinoBusy||!casinoSessionValid()||!casinoValidBet(casinoBet)||casinoChoices.length===0||total>Number(window.mmBalance||0);rs.textContent=casinoChoices.length>1?`MULTIBET · ${casinoFormat(total)} MM 🎲`:'SPIN 🎡';}const bs=document.getElementById('blackjackStart');if(bs)bs.disabled=casinoBusy||blackjackActive||!casinoSessionValid()||!casinoValidBet(casinoBet)||Number(window.mmBalance||0)<casinoBet;const a=document.getElementById('blackjackActions');if(a)a.hidden=!blackjackActive;const h=document.getElementById('blackjackHit'),st=document.getElementById('blackjackStand');if(h)h.disabled=casinoBusy||!blackjackActive;if(st)st.disabled=casinoBusy||!blackjackActive;const dbl=document.getElementById('blackjackDouble'),spl=document.getElementById('blackjackSplit');if(dbl)dbl.disabled=casinoBusy||!blackjackCanDouble()||Number(window.mmBalance||0)<casinoBet;if(spl)spl.disabled=casinoBusy||!blackjackCanSplit()||Number(window.mmBalance||0)<casinoBet;const ss=document.getElementById('slotsSpin');if(ss)ss.disabled=casinoBusy||!casinoSessionValid()||!casinoValidBet(casinoBet)||Number(window.mmBalance||0)<casinoBet;const sat=document.getElementById('slotsAutoToggle');if(sat){sat.disabled=casinoBusy&&!slotsAutoOn?true:(!casinoSessionValid()||!casinoValidBet(casinoBet))&&!slotsAutoOn;sat.textContent=`Auto-Spin: ${slotsAutoOn?'ON':'OFF'}`;sat.setAttribute('aria-pressed',String(slotsAutoOn));}}
function setCasinoBet(value){const n=Number(value);if(!casinoValidBet(n)){setCasinoStatus('Enter a whole-number bet of at least 10 MM.');return false;}if(n>Number(window.mmBalance||0)){setCasinoStatus('Not enough MM for this bet.');return false;}casinoBet=n;renderCasino();return true;}
window.setCasinoBet=setCasinoBet;
function showGame(game){if(casinoBusy)return;if(game!=='slots'&&slotsAutoOn)slotsAutoStop();casinoGame=game;renderCasino();}
function animateSelectedChip(button,bet){const chip=document.createElement('span');chip.className='casino-chip';chip.textContent=bet;button.appendChild(chip);requestAnimationFrame(()=>chip.classList.add('chip-landed'));}
function removeSelectedChip(button){button.querySelectorAll('.casino-chip').forEach(c=>c.remove());}
function setRouletteChoice(choice){if(casinoBusy||!casinoSessionValid())return;const b=document.querySelector(`#rouletteBetChoices [data-choice="${CSS.escape(choice)}"]`);if(casinoChoices.includes(choice)){casinoChoices=casinoChoices.filter(x=>x!==choice);if(b)removeSelectedChip(b);}else{if(casinoChoices.length>=12)return;if(!casinoValidBet(casinoBet)){setCasinoStatus('Enter a valid bet first.');return;}if(selectedRouletteTotal()+casinoBet>Number(window.mmBalance||0)){setCasinoStatus('Not enough MM for this multibet.');return;}casinoChoices=[...casinoChoices,choice];if(b)animateSelectedChip(b,casinoBet);}renderCasino();}
function cardNode(card,hidden=false){const e=document.createElement('div');e.className=`bj-card${hidden?' hidden-card':''}`;if(hidden){e.textContent='🂠';return e;}const red=card.suit==='♥'||card.suit==='♦';e.innerHTML=`<span class="bj-rank ${red?'red':''}">${card.rank}</span><span class="bj-suit ${red?'red':''}">${card.suit}</span>`;return e;}
function renderBlackjack(data,reveal=false){const d=document.getElementById('bjDealerCards'),p=document.getElementById('bjPlayerCards');if(!d||!p)return;d.replaceChildren();p.replaceChildren();(data.dealer_cards||[]).forEach((c,i)=>d.append(cardNode(c,!reveal&&i>0)));(data.player_cards||[]).forEach(c=>p.append(cardNode(c)));const pv=document.getElementById('bjPlayerValue'),dv=document.getElementById('bjDealerValue');if(pv)pv.textContent=data.player_value??'—';if(dv)dv.textContent=reveal?(data.dealer_value??'—'):'?';
  const isSplit=Boolean(data.is_split),h1Label=document.getElementById('bjHand1Label'),h1Side=document.getElementById('bjHand1Side'),h2Side=document.getElementById('bjHand2Side'),h2Cards=document.getElementById('bjHand2Cards'),h2Value=document.getElementById('bjHand2Value');
  if(h1Label)h1Label.textContent=isSplit?'Hand 1':'You';
  if(h2Side)h2Side.hidden=!isSplit;
  if(isSplit&&h2Cards){h2Cards.replaceChildren();(data.hand2_cards||[]).forEach(c=>h2Cards.append(cardNode(c)));if(h2Value)h2Value.textContent=data.hand2_value??'—';}
  const activeHand=Number(data.active_hand||1),notFinished=!data.finished;
  if(h1Side)h1Side.classList.toggle('bj-hand-active',isSplit&&notFinished&&activeHand===1);
  if(h2Side)h2Side.classList.toggle('bj-hand-active',isSplit&&notFinished&&activeHand===2);
  requestAnimationFrame(()=>document.querySelectorAll('.bj-card').forEach((c,i)=>setTimeout(()=>c.classList.add('dealt'),i*70)));}
function blackjackCanDouble(){if(!blackjackData||!blackjackActive)return false;const activeHand=Number(blackjackData.active_hand||1);const cards=activeHand===1?blackjackData.player_cards:blackjackData.hand2_cards;return Array.isArray(cards)&&cards.length===2;}
function blackjackCanSplit(){if(!blackjackData||!blackjackActive)return false;if(blackjackData.is_split)return false;const cards=blackjackData.player_cards;if(!Array.isArray(cards)||cards.length!==2)return false;return cards[0]?.rank===cards[1]?.rank;}
function blackjackMessage(status,payout){return({active:'Your move.',blackjack:'🃏 BLACKJACK! +3:2',won:'🎉 You win!',lost:'💥 Dealer wins.',push:'🤝 Push — your bet is returned.'}[status]||`Result: ${status}${payout?` · +${casinoFormat(payout)} MM`:''}`);}
function blackjackStatusMessage(d){const single={blackjack:'🃏 BLACKJACK! +3:2',won:'🎉 You win!',lost:'💥 Dealer wins.',push:'🤝 Push — your bet is returned.'};if(!d.finished){if(d.is_split&&Number(d.active_hand)===2&&d.status!=='active')return d.status==='lost'?'Hand 1 busts. Playing Hand 2…':'Hand 1 done. Playing Hand 2…';return 'Your move.';}if(!d.is_split)return single[d.status]||`Result: ${d.status}${d.payout?` · +${casinoFormat(d.payout)} MM`:''}`;const total=Number(d.payout||0)+Number(d.hand2_payout||0);return `Hand 1: ${d.status} · Hand 2: ${d.hand2_status}${total?` · +${casinoFormat(total)} MM`:' · no win'}`;}
async function loadCasinoStatus(){if(!casinoSessionValid())return;try{const r=await casinoFetch({action:'status'}),d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||`HTTP ${r.status}`);setBalanceFromCasino(d.balance);const active=d.active_blackjack;blackjackRoundId=active?.round_id||null;blackjackActive=Boolean(active);blackjackData=active||null;if(active){renderBlackjack(active,false);const s=document.getElementById('blackjackStatus');if(s)s.textContent='♠️ Resumed blackjack round — your move.';}renderCasino();}catch(e){setCasinoStatus(casinoError(e,'Casino'));}}
function stopRouletteAnimation(){if(rouletteAnimationFrame!==null){cancelAnimationFrame(rouletteAnimationFrame);rouletteAnimationFrame=null;}}
function animateRouletteWheel(wheel,ball,duration=3000){stopRouletteAnimation();if(!wheel)return Promise.resolve();wheel.style.transition='none';const start=performance.now(),angleTotal=1440;return new Promise(resolve=>{const tick=now=>{const t=Math.min(1,(now-start)/duration);const angle=angleTotal*t;wheel.style.transform=`translate3d(0,0,0) rotate(${angle}deg)`;if(ball){const orbit=-angle*1.9;ball.style.transform=`translate(-50%,-50%) rotate(${orbit}deg) translateY(-67px)`;}if(t<1)rouletteAnimationFrame=requestAnimationFrame(tick);else{rouletteAnimationFrame=null;resolve();}};rouletteAnimationFrame=requestAnimationFrame(tick);});}
async function playCasinoRoulette(){if(casinoBusy||!casinoSessionValid())return;if(!casinoValidBet(casinoBet))return;if(!casinoChoices.length||casinoChoices.length>12)return;const totalBet=selectedRouletteTotal();if(Number(window.mmBalance||0)<totalBet){setCasinoStatus('Not enough MM for this multibet.');return;}casinoBusy=true;renderCasino();const wheel=document.getElementById('rouletteWheel'),ball=document.querySelector('.roulette-ball'),result=document.getElementById('rouletteResult');if(result)result.textContent='…';setCasinoStatus(`${casinoChoices.length>1?'Multibet':'Roulette'}: ${casinoFormat(totalBet)} MM — la roue tourne...`);try{const request=casinoFetch({action:'roulette',bet:casinoBet,choice:casinoChoices.join(','),operation_key:casinoOperationKey()});const animation=animateRouletteWheel(wheel,ball,3000);const r=await request,d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||`HTTP ${r.status}`);await animation;setBalanceFromCasino(d.balance);if(result){result.textContent=Number(d.result_number);result.className=`roulette-number ${d.result_color}`;}setCasinoStatus(d.won?`🎉 ${d.result_number} ${d.result_color} — +${casinoFormat(d.net_change)} MM.`:`🎲 ${d.result_number} ${d.result_color} — -${casinoFormat(totalBet)} MM.`);}catch(e){stopRouletteAnimation();if(wheel)wheel.style.transform='translate3d(0,0,0)';if(ball)ball.style.transform='translate(-50%,-50%) translateY(-67px)';setCasinoStatus(casinoError(e,'Roulette'));}finally{casinoBusy=false;renderCasino();}}
async function startBlackjack(){if(casinoBusy||blackjackActive||!casinoSessionValid())return;if(!casinoValidBet(casinoBet))return;if(Number(window.mmBalance||0)<casinoBet){setCasinoStatus('Not enough MM for this bet.');return;}casinoBusy=true;blackjackData=null;const h2=document.getElementById('bjHand2Side');if(h2)h2.hidden=true;renderCasino();const s=document.getElementById('blackjackStatus');if(s)s.textContent='Dealing cards...';try{const r=await casinoFetch({action:'blackjack_start',bet:casinoBet,operation_key:casinoOperationKey()}),d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||`HTTP ${r.status}`);setBalanceFromCasino(d.balance);blackjackRoundId=d.round_id;blackjackData=d;blackjackActive=!d.finished;renderBlackjack(d,Boolean(d.finished));if(s)s.textContent=blackjackStatusMessage(d);if(!blackjackActive)blackjackRoundId=null;}catch(e){if(s)s.textContent=casinoError(e,'Blackjack');}finally{casinoBusy=false;renderCasino();}}
async function blackjackAction(action){if(casinoBusy||!blackjackActive||!blackjackRoundId)return;casinoBusy=true;renderCasino();const s=document.getElementById('blackjackStatus');const messages={hit:'Drawing a card...',double:'Doubling down...',split:'Splitting your hand...',stand:'Dealer is playing...'};if(s)s.textContent=messages[action]||'Playing...';try{const r=await casinoFetch({action:'blackjack_action',round_id:blackjackRoundId,blackjack_action:action,operation_key:casinoOperationKey()}),d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||`HTTP ${r.status}`);setBalanceFromCasino(d.balance);blackjackData=d;renderBlackjack(d,Boolean(d.finished));blackjackActive=!d.finished;if(s)s.textContent=blackjackStatusMessage(d);if(!blackjackActive)blackjackRoundId=null;}catch(e){const map={BLACKJACK_SPLIT_NOT_ALLOWED:'This hand cannot be split.',BLACKJACK_DOUBLE_NOT_ALLOWED:'This hand cannot be doubled.'};if(s)s.textContent=map[e.message]||casinoError(e,'Blackjack');}finally{casinoBusy=false;renderCasino();}}
function slotsAutoStop(message){slotsAutoOn=false;if(slotsAutoTimer){clearTimeout(slotsAutoTimer);slotsAutoTimer=null;}if(message)setCasinoStatus(message);renderCasino();}
function slotsAutoScheduleNext(){if(!slotsAutoOn)return;if(slotsAutoTimer)clearTimeout(slotsAutoTimer);slotsAutoTimer=window.setTimeout(()=>{slotsAutoTimer=null;if(!slotsAutoOn)return;if(casinoGame!=='slots'||document.body.dataset.mmPage!=='casino'){slotsAutoStop();return;}if(!casinoSessionValid()){slotsAutoStop('Auto-spin stopped: session expired.');return;}if(!casinoValidBet(casinoBet)||Number(window.mmBalance||0)<casinoBet){slotsAutoStop('Auto-spin stopped: not enough MM.');return;}spinSlots();},1300);}
function toggleSlotsAuto(){if(slotsAutoOn){slotsAutoStop();return;}if(casinoBusy)return;if(!casinoSessionValid()||!casinoValidBet(casinoBet)){setCasinoStatus('Choose a valid bet first.');return;}if(Number(window.mmBalance||0)<casinoBet){setCasinoStatus('Not enough MM for this bet.');return;}slotsAutoOn=true;renderCasino();spinSlots();}
async function spinSlots(){if(casinoBusy||!casinoSessionValid())return;if(!casinoValidBet(casinoBet))return;if(Number(window.mmBalance||0)<casinoBet){setCasinoStatus('Not enough MM for this bet.');if(slotsAutoOn)slotsAutoStop();return;}casinoBusy=true;renderCasino();const s=document.getElementById('slotsStatus'),m=document.getElementById('slotMachine');if(s)s.textContent='Spinning...';if(m){m.classList.remove('slot-spinning','slot-win');void m.offsetWidth;m.classList.add('slot-spinning');}try{const r=await casinoFetch({action:'slots',bet:casinoBet,operation_key:casinoOperationKey()}),d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||`HTTP ${r.status}`);setTimeout(()=>{(d.symbols||[]).forEach((x,i)=>{const e=document.getElementById(`slot${i}`);if(e)e.textContent=x;});if(m)m.classList.remove('slot-spinning');},650);setBalanceFromCasino(d.balance);const win=Number(d.payout)>0;if(s)s.textContent=(slotsAutoOn?'🔁 ':'')+(win?`🎉 WIN ×${d.multiplier} · +${casinoFormat(d.payout)} MM`:'No match — try again.');if(win&&m)setTimeout(()=>m.classList.add('slot-win'),680);if(slotsAutoOn)slotsAutoScheduleNext();}catch(e){if(m)m.classList.remove('slot-spinning');if(s)s.textContent=casinoError(e,'Slots');if(slotsAutoOn)slotsAutoStop();}finally{casinoBusy=false;renderCasino();}}
function injectRouletteStyle(){if(document.getElementById('casinoRouletteStyle'))return;const s=document.createElement('style');s.id='casinoRouletteStyle';s.textContent=`#rouletteBetChoices{margin-top:8px}.roulette-choice-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-bottom:12px}.roulette-choice-grid button{position:relative;overflow:visible;margin:0!important;min-height:46px;padding:8px 4px;background:#182230;color:#dbe1e9;border:1px solid #263142;border-radius:12px;font-weight:800;font-size:12px}.roulette-choice-grid button.selected{background:#163323;color:#63e69a;border-color:#3a8054}.roulette-choice-grid button.red{color:#ff8b91}.roulette-choice-grid button.black{color:#fff}.roulette-choice-grid button small{display:block;font-size:9px;opacity:.72;margin-top:2px}.casino-chip{position:absolute;right:8px;top:-13px;z-index:5;width:30px;height:30px;border-radius:50%;display:grid;place-items:center;background:#101722;border:3px dashed #63e69a;box-shadow:0 3px 12px #0008;color:#63e69a;font-size:9px;font-weight:900;transform:translateY(-18px) scale(.55) rotate(-20deg);opacity:0;pointer-events:none}.casino-chip.chip-landed{animation:casinoChipLand .42s cubic-bezier(.2,.9,.25,1.2) forwards}.roulette-choice-button.selected .casino-chip{opacity:1;transform:translateY(0) scale(1)}@keyframes casinoChipLand{0%{opacity:0;transform:translateY(-22px) scale(.45) rotate(-25deg)}65%{opacity:1;transform:translateY(3px) scale(1.08) rotate(8deg)}100%{opacity:1;transform:translateY(0) scale(1) rotate(0)}}.roulette-wheel{transition:none!important;animation:none!important}.roulette-ball{animation:none!important;will-change:transform}.roulette-spin{animation:none!important}.casino-custom-bet{box-sizing:border-box;width:100%;min-width:0;height:48px;padding:0 12px;border:1px solid #263142;border-radius:12px;background:#182230;color:#f4f7fb;font:inherit;font-weight:800;text-align:center;outline:none}.casino-custom-bet::placeholder{color:#8d9aae}.casino-custom-bet:focus{border-color:#4edb8a;box-shadow:0 0 0 2px #4edb8a22}.casino-custom-bet.selected{border-color:#3a8054;background:#163323;color:#63e69a}.casino-custom-bet[aria-invalid="true"]{border-color:#b94b56}.casino-custom-bet:disabled{opacity:.55}`;document.head.appendChild(s);}
function bindCasino(){injectRouletteStyle();ensureRouletteChoices();document.querySelectorAll('.casino-tab').forEach(b=>b.addEventListener('click',()=>showGame(b.dataset.game)));document.querySelectorAll('.casino-bets [data-bet]').forEach(b=>b.addEventListener('click',()=>setCasinoBet(b.dataset.bet)));document.querySelectorAll('.casino-custom-bet').forEach(i=>{i.addEventListener('input',()=>{const n=Number(i.value);if(casinoValidBet(n)&&n<=Number(window.mmBalance||0))setCasinoBet(n);else{renderCasino();i.value=i.value.replace(/[^0-9]/g,'');}});i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();setCasinoBet(i.value);i.blur();}});});document.querySelectorAll('#rouletteBetChoices [data-choice]').forEach(b=>b.addEventListener('click',()=>setRouletteChoice(b.dataset.choice)));document.getElementById('rouletteSpin')?.addEventListener('click',playCasinoRoulette);document.getElementById('blackjackStart')?.addEventListener('click',startBlackjack);document.getElementById('blackjackHit')?.addEventListener('click',()=>blackjackAction('hit'));document.getElementById('blackjackStand')?.addEventListener('click',()=>blackjackAction('stand'));document.getElementById('blackjackDouble')?.addEventListener('click',()=>blackjackAction('double'));document.getElementById('blackjackSplit')?.addEventListener('click',()=>blackjackAction('split'));document.getElementById('slotsSpin')?.addEventListener('click',spinSlots);document.getElementById('slotsAutoToggle')?.addEventListener('click',toggleSlotsAuto);renderCasino();}
window.addEventListener('make-money-authenticated',()=>{ensureRouletteChoices();renderCasino();loadCasinoStatus();});window.addEventListener('make-money-balance-updated',()=>renderCasino());if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindCasino);else bindCasino();