const HOME_RANKING_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-ranking';
const HOME_CASES_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-cases';
const HOME_MINING_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-mining';
const HOME_JOBS_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-jobs';
const HOME_RE_API='https://klvpeopoziausjvefaek.supabase.co/functions/v1/make-money-real-estate';
const homeJson=async(url,body)=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${window.mmSessionToken}`},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok||!d?.ok)throw new Error(d?.error||`HTTP ${r.status}`);return d;};
let homeItems=[],homeAssets=[];
function homeFmt(v){return Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2});}
function homeProfileOpen(){const m=document.getElementById('profileSheet');if(m)m.hidden=false;loadHomeRank();}
function homeProfileClose(){const m=document.getElementById('profileSheet');if(m)m.hidden=true;}
async function loadHomeRank(){const e=document.getElementById('profileRank');if(!e||!window.mmSessionToken)return;try{const d=await homeJson(HOME_RANKING_API,{limit:100});const me=(d.ranking||[]).find(x=>x.is_me);e.textContent=me?`#${Number(me.rank)}`:'—';}catch{e.textContent='—';}}
function homePlayTime(){const key='mm_home_play_seconds';const current=Number(localStorage.getItem(key)||0);const started=Number(window.mmHomeSessionStarted||Date.now());const total=current+Math.max(0,Math.floor((Date.now()-started)/1000));localStorage.setItem(key,String(total));const h=Math.floor(total/3600),m=Math.floor((total%3600)/60);return `${h}h ${m}m`;}
function renderHomeProfile(){const img=document.querySelector('#avatar img');const button=document.getElementById('homeProfileButton');const large=document.getElementById('profileAvatarLarge');if(img&&button)button.replaceChildren(img.cloneNode(true));else if(button)button.innerHTML='<span>◎</span>';if(large)large.replaceChildren(img?img.cloneNode(true):Object.assign(document.createElement('span'),{textContent:'◎'}));const name=document.getElementById('name')?.textContent||'Player';const username=document.getElementById('username')?.textContent||'Telegram user';const w=document.getElementById('homeWelcomeName');if(w)w.textContent=name;const pn=document.getElementById('profileName');if(pn)pn.textContent=name;const pu=document.getElementById('profileUsername');if(pu)pu.textContent=username;const pt=document.getElementById('profilePlayTime');if(pt)pt.textContent=homePlayTime();}
function addHomeAsset(icon,name,sub,rate,unit='h'){homeAssets.push({icon,name,sub,rate:Number(rate||0),unit});}
function renderHomeAssets(){const list=document.getElementById('homeAssetList'),income=document.getElementById('homeAssetsIncome'),items=document.getElementById('homeItemGrid'),count=document.getElementById('homeItemsCount');if(!list)return;list.replaceChildren();let perHour=0;for(const a of homeAssets){perHour+=a.unit==='day'?a.rate/24:a.rate;const row=document.createElement('div');row.className='home-asset-row';row.innerHTML=`<div class="home-asset-icon">${a.icon}</div><div class="home-asset-info"><strong>${a.name}</strong><small>${a.sub}</small></div><strong class="home-asset-rate">+${homeFmt(a.rate)} / ${a.unit}</strong>`;list.append(row);}if(!homeAssets.length)list.innerHTML='<div class="home-empty">No active income assets yet.</div>';if(income)income.textContent=`+${homeFmt(perHour)} MM / hour`;if(items){items.replaceChildren();homeItems.slice(0,6).forEach(i=>{const c=document.createElement('div');c.className='home-item-card';c.innerHTML=`<div class="item-visual">✦</div><strong>${i.display_name}</strong><small>${homeFmt(i.sell_value)} MM</small>`;items.append(c);});if(!homeItems.length)items.innerHTML='<div class="home-empty">No items collected yet.</div>';}if(count)count.textContent=`Items: ${homeItems.reduce((n,i)=>n+Number(i.quantity||0),0)}`;}
async function loadHomeAssets(){if(!window.mmSessionToken)return;homeAssets=[];homeItems=[];const [mining,jobs,re,items]=await Promise.allSettled([homeJson(HOME_MINING_API,{action:'status'}),homeJson(HOME_JOBS_API,{action:'list'}),homeJson(HOME_RE_API,{action:'list'}),homeJson(HOME_CASES_API,{action:'status'})]);if(mining.status==='fulfilled'){const current=(mining.value.mining||[]).find(x=>x.owned)||(mining.value.mining||[])[0];if(current)addHomeAsset('⛏️',current.name||'Mining',`Level ${current.level||1}`,Number(current.rate_per_hour||0),'h');}if(jobs.status==='fulfilled'){const active=(jobs.value.jobs||[]).find(x=>x.active);if(active)addHomeAsset('💼',active.name||'Job','Active job',Number(active.income_per_hour||0),'h');}if(re.status==='fulfilled'){for(const p of (re.value.properties||[]).filter(x=>Number(x.owned_units||0)>0))addHomeAsset('🏢',p.name||'Property',`${p.owned_units} owned`,Number(p.income_per_day||0),'day');}if(items.status==='fulfilled')homeItems=Array.isArray(items.value.inventory)?items.value.inventory:[];renderHomeAssets();}
function homeBind(){window.mmHomeSessionStarted=Date.now();document.getElementById('homeProfileButton')?.addEventListener('click',homeProfileOpen);document.getElementById('profileClose')?.addEventListener('click',homeProfileClose);document.getElementById('profileSheet')?.addEventListener('click',e=>{if(e.target.id==='profileSheet')homeProfileClose();});document.getElementById('homeInventoryButton')?.addEventListener('click',()=>window.mmNavigate?.('inventory'));window.addEventListener('make-money-authenticated',()=>{renderHomeProfile();loadHomeAssets();});window.addEventListener('make-money-balance-updated',()=>loadHomeAssets());if(window.mmSessionToken){renderHomeProfile();loadHomeAssets();}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',homeBind,{once:true});else homeBind();