import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const cors={"Access-Control-Allow-Origin":"https://sniperscoop2-spec.github.io","Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","Vary":"Origin"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
async function sha256Hex(value:string){const d=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));return Array.from(d).map(x=>x.toString(16).padStart(2,"0")).join("");}
async function rpc(name:string,args:Record<string,unknown>){const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw new Error("server_credentials_unavailable");const r=await fetch(`${url}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify(args)});const text=await r.text();if(!r.ok)throw new Error(text||`rpc_${r.status}`);return text?JSON.parse(text):null;}
const first=(x:any)=>Array.isArray(x)?x[0]:x;
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({ok:false,error:'POST_REQUIRED'},405);try{const auth=req.headers.get('authorization')??'';if(!auth.startsWith('Bearer '))return json({ok:false,error:'UNAUTHORIZED'},401);const token=auth.slice(7).trim();if(!/^[A-Za-z0-9_-]{40,256}$/.test(token))return json({ok:false,error:'UNAUTHORIZED'},401);const sessionHash=await sha256Hex(token);const body=await req.json().catch(()=>({}));const action=body.action;
if(action==='status'){const d=first(await rpc('make_money_cases_status',{p_session_hash:sessionHash}));return json({ok:true,...d});}
if(action==='open'){const caseId=typeof body.case_id==='string'?body.case_id:'';const key=typeof body.operation_key==='string'?body.operation_key:'';if(!/^(case_50|case_500|case_5000|case_50000|case_500000)$/.test(caseId))throw new Error('invalid_case');if(!/^[A-Za-z0-9_-]{16,128}$/.test(key))throw new Error('invalid_operation_key');const d=first(await rpc('make_money_case_open',{p_session_hash:sessionHash,p_case_id:caseId,p_operation_key:key}));return json({ok:true,...d});}
if(action==='sell'){const item=typeof body.item_id==='string'?body.item_id:'';const qty=Number(body.quantity);const key=typeof body.operation_key==='string'?body.operation_key:'';if(!/^case(?:50|500|5000|50000|500000)_[a-z0-9_-]+$/.test(item)||!Number.isInteger(qty)||qty<1)throw new Error('invalid_quantity');if(!/^[A-Za-z0-9_-]{16,128}$/.test(key))throw new Error('invalid_operation_key');const d=first(await rpc('make_money_inventory_sell',{p_session_hash:sessionHash,p_item_id:item,p_quantity:qty,p_operation_key:key}));return json({ok:true,...d});}
if(action==='sell_all'){const key=typeof body.operation_key==='string'?body.operation_key:'';if(!/^[A-Za-z0-9_-]{16,128}$/.test(key))throw new Error('invalid_operation_key');const d=first(await rpc('make_money_inventory_sell_all',{p_session_hash:sessionHash,p_operation_key:key}));return json({ok:true,...d});}
return json({ok:false,error:'INVALID_ACTION'},400);
}catch(e){const m=e instanceof Error?e.message:String(e);if(m.includes('invalid_or_expired_session'))return json({ok:false,error:'SESSION_EXPIRED'},401);if(m.includes('invalid_session'))return json({ok:false,error:'UNAUTHORIZED'},401);if(m.includes('insufficient_balance'))return json({ok:false,error:'INSUFFICIENT_BALANCE'},409);if(m.includes('invalid_case'))return json({ok:false,error:'INVALID_CASE'},400);if(m.includes('invalid_operation_key'))return json({ok:false,error:'INVALID_OPERATION_KEY'},400);if(m.includes('item_not_found'))return json({ok:false,error:'ITEM_NOT_FOUND'},404);if(m.includes('insufficient_items'))return json({ok:false,error:'INSUFFICIENT_ITEMS'},409);if(m.includes('invalid_quantity'))return json({ok:false,error:'INVALID_QUANTITY'},400);if(m.includes('invalid_item'))return json({ok:false,error:'INVALID_ITEM'},400);if(m.includes('operation_key_reused'))return json({ok:false,error:'OPERATION_REUSED'},409);console.error('make-money-cases',m);return json({ok:false,error:'CASES_SERVER_ERROR'},500);}});