-- Fix casino RPCs: PL/pgSQL variable/column ambiguity and missing transaction balance_after expression.
-- Applied to production with the same definitions.

CREATE OR REPLACE FUNCTION public.make_money_casino_blackjack_start(p_session_hash text, p_bet numeric, p_operation_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare pid uuid;bal numeric(30,4);wager numeric(30,4);day date;b numeric(20,0);pc jsonb:='[]';dc jsonb:='[]';card jsonb;pv int;dv int;st text:='active';payout numeric:=0;newbal numeric;existing jsonb;lim numeric:=1000;rid uuid;
begin
 if p_session_hash is null or p_session_hash !~ '^[0-9a-f]{64}$' then raise exception 'invalid_session';end if;if p_operation_key is null or p_operation_key !~ '^[A-Za-z0-9_-]{16,128}$' then raise exception 'invalid_operation_key';end if;b:=trunc(coalesce(p_bet,0));if b<10 or b>100 then raise exception 'invalid_bet';end if;
 select player_id into pid from make_money_sessions where token_hash=p_session_hash and revoked_at is null and expires_at>now() limit 1;if pid is null then raise exception 'invalid_or_expired_session';end if;perform pg_advisory_xact_lock(hashtextextended(pid::text||':bj:start:'||p_operation_key,0));
 select jsonb_build_object('game','blackjack','round_id',r.id,'player_cards',r.player_cards,'dealer_cards',case when r.status='active' then jsonb_build_array(r.dealer_cards->0) else r.dealer_cards end,'status',r.status,'payout',r.payout,'balance',r.balance_after,'player_value',make_money_casino_blackjack_value(r.player_cards),'dealer_value',case when r.status='active' then make_money_casino_blackjack_value(jsonb_build_array(r.dealer_cards->0)) else make_money_casino_blackjack_value(r.dealer_cards) end) into existing from make_money_casino_blackjack_rounds r where r.player_id=pid and r.operation_key=p_operation_key limit 1;if existing is not null then return existing;end if;
 select balance into bal from make_money_players where id=pid for update;if bal is null then raise exception 'player_not_found';end if;if bal<b then raise exception 'insufficient_balance';end if;
 select coalesce(wagered_today,0),wager_day into wager,day from make_money_casino_daily where player_id=pid for update;if not found then insert into make_money_casino_daily(player_id,wager_day,wagered_today) values(pid,current_date,0) on conflict(player_id) do nothing;select coalesce(wagered_today,0),wager_day into wager,day from make_money_casino_daily where player_id=pid for update;end if;if day<>current_date then wager:=0;update make_money_casino_daily set wager_day=current_date,wagered_today=0,updated_at=now() where player_id=pid;end if;if wager+b>lim then raise exception 'daily_wager_limit_reached';end if;
 card:=make_money_casino_draw_card(pc);pc:=pc||jsonb_build_array(card);card:=make_money_casino_draw_card(pc);dc:=dc||jsonb_build_array(card);card:=make_money_casino_draw_card(pc||dc);pc:=pc||jsonb_build_array(card);card:=make_money_casino_draw_card(pc||dc);dc:=dc||jsonb_build_array(card);
 pv:=make_money_casino_blackjack_value(pc);dv:=make_money_casino_blackjack_value(dc);if pv=21 then if dv=21 then st:='push';payout:=b;else st:='blackjack';payout:=b*5/2;end if;elsif dv=21 then st:='lost';payout:=0;end if;newbal:=bal-b+case when st='active' then 0 else payout end;
 insert into make_money_casino_blackjack_rounds(player_id,operation_key,bet,player_cards,dealer_cards,status,payout,balance_after,finished_at) values(pid,p_operation_key,b,pc,dc,st,payout,newbal,case when st='active' then null else now() end) returning id into rid;
 update make_money_players set balance=newbal,updated_at=now() where id=pid;update make_money_casino_daily set wagered_today=wager+b,updated_at=now() where player_id=pid;
 insert into make_money_transactions(player_id,type,amount,balance_before,balance_after,reference,metadata) values(pid,'casino_blackjack',newbal-bal,bal,newbal,p_operation_key,jsonb_build_object('game','blackjack','action','start','bet',b,'status',st,'payout',payout));
 return jsonb_build_object('game','blackjack','round_id',rid,'player_cards',pc,'dealer_cards',case when st='active' then jsonb_build_array(dc->0) else dc end,'status',st,'payout',payout,'balance',newbal,'wagered_today',wager+b,'daily_wager_limit',lim,'player_value',pv,'dealer_value',case when st='active' then make_money_casino_blackjack_value(jsonb_build_array(dc->0)) else dv end);
end;$function$;

CREATE OR REPLACE FUNCTION public.make_money_casino_slots(p_session_hash text, p_bet numeric, p_operation_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare pid uuid;bal numeric;wager numeric;day date;b numeric(20,0);lim numeric:=1000;a int;c int;d int;syms text[];payout numeric:=0;newbal numeric;mult numeric:=0;existing jsonb;
begin
 if p_session_hash is null or p_session_hash !~ '^[0-9a-f]{64}$' then raise exception 'invalid_session';end if;if p_operation_key is null or p_operation_key !~ '^[A-Za-z0-9_-]{16,128}$' then raise exception 'invalid_operation_key';end if;b:=trunc(coalesce(p_bet,0));if b<10 or b>100 then raise exception 'invalid_bet';end if;select player_id into pid from make_money_sessions where token_hash=p_session_hash and revoked_at is null and expires_at>now() limit 1;if pid is null then raise exception 'invalid_or_expired_session';end if;perform pg_advisory_xact_lock(hashtextextended(pid::text||':slots:'||p_operation_key,0));
 select jsonb_build_object('game','slots','symbols',s.symbols,'payout',s.payout,'net_change',s.payout-s.bet,'balance',s.balance_after,'wagered_today',0,'daily_wager_limit',lim,'multiplier',case when s.payout=0 then 0 else s.payout/s.bet end) into existing from make_money_casino_slots_spins s where s.player_id=pid and s.operation_key=p_operation_key;if existing is not null then return existing;end if;
 select balance into bal from make_money_players where id=pid for update;if bal is null then raise exception 'player_not_found';end if;if bal<b then raise exception 'insufficient_balance';end if;select coalesce(wagered_today,0),wager_day into wager,day from make_money_casino_daily where player_id=pid for update;if not found then insert into make_money_casino_daily(player_id,wager_day,wagered_today) values(pid,current_date,0) on conflict(player_id) do nothing;select coalesce(wagered_today,0),wager_day into wager,day from make_money_casino_daily where player_id=pid for update;end if;if day<>current_date then wager:=0;update make_money_casino_daily set wager_day=current_date,wagered_today=0,updated_at=now() where player_id=pid;end if;if wager+b>lim then raise exception 'daily_wager_limit_reached';end if;
 a:=floor(random()*100)::int;c:=floor(random()*100)::int;d:=floor(random()*100)::int;syms:=array[case when a<4 then '7️⃣' when a<14 then '💎' when a<29 then 'BAR' when a<49 then '🔔' when a<74 then '🍋' else '🍒' end,case when c<4 then '7️⃣' when c<14 then '💎' when c<29 then 'BAR' when c<49 then '🔔' when c<74 then '🍋' else '🍒' end,case when d<4 then '7️⃣' when d<14 then '💎' when d<29 then 'BAR' when d<49 then '🔔' when d<74 then '🍋' else '🍒' end];
 if syms[1]=syms[2] and syms[2]=syms[3] then mult:=case syms[1] when '7️⃣' then 20 when '💎' then 10 when 'BAR' then 7 when '🔔' then 5 when '🍋' then 3 else 2 end;elsif(syms[1]='🍒' and syms[2]='🍒') or(syms[2]='🍒' and syms[3]='🍒') then mult:=1;end if;payout:=b*mult;newbal:=bal-b+payout;
 insert into make_money_casino_slots_spins(player_id,operation_key,bet,symbols,payout,balance_after) values(pid,p_operation_key,b,syms,payout,newbal);update make_money_players set balance=newbal,updated_at=now() where id=pid;update make_money_casino_daily set wagered_today=wager+b,updated_at=now() where player_id=pid;insert into make_money_transactions(player_id,type,amount,balance_before,balance_after,reference,metadata) values(pid,'casino_slots',newbal-bal,bal,newbal,p_operation_key,jsonb_build_object('game','slots','bet',b,'symbols',syms,'payout',payout,'multiplier',mult));return jsonb_build_object('game','slots','symbols',syms,'payout',payout,'net_change',payout-b,'balance',newbal,'wagered_today',wager+b,'daily_wager_limit',lim,'multiplier',mult);
end;$function$;
